### ISSUE TITLE
Enabling fast mode prevents the other mode switching keys.

### ISSUE THREAD

**Issue by demolitions** [FedeDP/ncursesFM#2]
This maybe should only be a helper refinement:
When you enable fast browse mode, the keys other than arrows and comma are used as file selection shortcuts, this means that "t" does not open a new tab anymore, "h" does not toggle hidden files, and so on.

The issue isn't very relevant instantly when you enable fast browse, but becomes so after you select a file, since the "I:" row does not say "Fast browse mode enabled" anymore, but the keys you pressed to select a file.

I don't know whether it should be better:
- having "Fast browse mode enabled" (or perhaps only "Fast") permanently written somewhere (for example, on the right of the "I:" row)
- disabling fast browse mode as soon as a key [^0-9a-z] is pressed.
- having the helper text reflect the change, as soon as you press "," the other keys may change color, or disappear, to turn back light grey (or visible) once fast browse mode is disabled.

**Comment by FedeDP** [comment]
I'm gonna go for the same thing as other bug report: instead of green, arrow will appear red (it recalls something like stamina mode or, well you know, something fast!).
Are you ok with my idea?

PS: i'm gonna make fast browse mode activable indipendently per-tab. As of now you can enable it for just one tab a time.
EDIT: i'm gonna let user select files in fast_browse_mode too.

**Comment by demolitions** [comment]
I didn't notice that fast browse mode was enabled only for the active tab.
Nice, arrow green for active tab, arrow red for active tab in fast browse, should be more than enough.
