### ISSUE TITLE
Preview Images and Documents

### ISSUE THREAD

**Issue by ghost** [FedeDP/ncursesFM#6]
Hi, as posted here on [reddit](https://www.reddit.com/r/linux/comments/4i4bm3/a_new_ncurses_filemanager_for_linux/d2vair4). 
How about a image preview feature? Maybe a feature to preview documents (pdf, odt, html).

I think it would be nice to have a fast CLI filemanager to manage my images.
Ranger also have this feature [http://ranger.nongnu.org/](http://ranger.nongnu.org/).

**Comment by FedeDP** [comment]
I'll look into that! Thanks for posting the issue here!

**Comment by FedeDP** [comment]
I'm currently working on it, it is kinda working right now to be honest, but i still need to fix some issues. :)
![screenshot_20160508_130939](https://cloud.githubusercontent.com/assets/5837210/15097515/e416851a-151d-11e6-8ce4-80f9574a1851.png)

**Comment by ghost** [comment]
Nice, this was a fast response :+1: 
Is it working with transparent Terminal? Like the popular urxvt?

**Comment by FedeDP** [comment]
Mmmh as stated here (the following guide seems that has provided great help to vifm and ranger developers) it seems urxvt should not render images with transparency enabled: http://blog.z3bra.org/2014/01/images-in-terminal.html
Btw i quickly tried and it seems to be working (well, 2 years passed since that blog post), BUT i do not use urxvt so i may have done some mistakes.
You'll be able to try yourself as soon as remaining issues got squashed :)

**Comment by FedeDP** [comment]
In "image_previewer" branch you can find a working version of the image previewer plus some other fixes and improvements all around (eg: per-user settings, reworked helper screen that now updates its content based on active tab mode, more evident active tab, in conf file user can now customize latest line ("sysinfo" line)  layout...and fixes all around the code)...yes i should have called it "develop" branch...

Btw i tested image preview with standard xterm and urxvt (as found in arch repos), and it's working perfectly fine. But your configuration may have some issues. 
Eg: in konsole i've still got an issue...so it depends a lot on how terminals manage screen.
Understandable, as terminal were not meant to display images.

So, let me know if you've got issues, thanks :) I'll try to fix them before merging into master!
Attach your terminal config too, so i can properly test.
And please, be aware of the limitations abovementioned!

Have a nice weekend, and thanks for your time! :)

**Comment by FedeDP** [comment]
PS, i forgot that: use 'j' to enable preview!

**Comment by FedeDP** [comment]
I'll close this as i removed image previewing support, and won't implement any kind of preview.
I think it is useless to have features that work inconsistently between terminal applications/systems.
In my opinion it is better not to have a feature, instead of having a feature that works on X systems, somewhat works on Y systems and doesn't work on Z systems.

Moreover, image preview (and previews in general) are somewhat too fancy for a terminal ncurses based fm.
