### ISSUE TITLE
Compiling on Debian stable (Jessie)

### ISSUE THREAD

**Issue by ghost** [FedeDP/ncursesFM#8]
I have installed all required and optional packages from your Ubuntu section in Install Instructions. Still get these Error messages on debian stable:
http://codepaste.net/7t52dc

I tried to build master and image_previewer branch. Both get the same error.

**Comment by FedeDP** [comment]
Hi!
Did you install libsystemd-dev?
Can you paste the output of
pkg-config --silence-errors --libs --cflags libsystemd

Thanks!

EDIT: wow, it seems libsystemd-dev won't carry sd-bus.h in debian jessie (https://packages.debian.org/jessie/amd64/libsystemd-dev/filelist). 
What version of systemd are you running?

**Comment by FedeDP** [comment]
Ok, that's because debian jessie ships systemd 215, while sd-bus API has been made public in 221 release.
Can you update systemd? Otherwise you can build with
make DISABLE_LIBSYSTEMD=1
but this would disable sd-bus support (iso mounting, device monitor/automounter, packages installation, upower signaling catching...)

EDIT: i pushed a new makefile to image_previewer branch, with a new check for systemd minimum version (221). It should now build on your pc. By the way, i'd try to update systemd, if you can. :)
